--[[
    BEGINNER GUIDE — Peds
    =====================

    File: cmg/prod/cfg/ped_cfg/peds.lua
    Purpose: This file contains configuration/data.

    How to read FiveM Lua:
      * RegisterNetEvent/AddEventHandler = code that runs when an event happens.
      * TriggerServerEvent = this client asks/tells the server to do something.
      * PlayerPedId() = your local GTA character (called a 'ped').
      * vector3/vector4 = world coordinates; vector4 also normally includes heading.
      * RageUI/NUI = menu or browser-based UI code.
      * CreateThread/Wait = code that can keep running without freezing the game.

]]
local cfg = {}

cfg.peds = {
    ["Normal"] ={
        --{name,modelName}
        ["config"] = {name="CMG Peds", permissions = {}},
        {"s_m_y_airworker","Air Worker"},
        {"a_m_y_jetski_01","Jetski Male"},
        {"g_m_m_armboss_01","Mafia Boss"},
        {"a_m_m_polynesian_01","Beach Male"},
        {"s_m_y_pestcont_01","Pest Control"},
        {"u_m_o_taphillbilly","Taphill Billy"},
        {"a_m_m_trampbeac_01","Homeless Male"},
        {"u_m_m_promourn_01","Mourning male"},
        {"u_m_y_mani","Mexican male"},
        {"a_m_y_vinewood_02","Hipster male"},
        {"s_m_m_movprem_01","Suited male"},
        {"csb_porndudes","Ripped male"},
        {"s_m_y_prismuscl_01","Prison male"},
        {"g_m_y_famfor_01","Gangster male"},
        {"g_m_y_mexgoon_03","Mexican goon"},
        {"a_m_m_salton_03","Black goon"},
        {"a_m_y_surfer_01","Surfer dude"},
        {"s_m_y_autopsy_01","Autopsy ped"},
        {"a_m_m_prolhost_01","Store employee"},
        {"a_m_y_eastsa_02","Eastside male"},
        {"a_m_y_musclbeac_01","Ripped male"},
        {"s_m_y_uscg_01","Coast Guard"},
        {"a_m_m_farmer_01","Farmer"},
        {"a_m_m_afriamer_01","Fat American"},
        {"s_m_y_barman_01","Barman"},
        {"s_m_o_busker_01","Busker"},
        {"a_m_m_golfer_01","Golfer"},
        {"u_m_m_bankman","Bank teller"},
        {"csb_fos_rep","Hippie male"},
        {"g_m_m_chiboss_01","Chinese Boss Male"},
        {"g_m_y_azteca_01","Azteca Male"},
        {"s_m_y_xmech_01","Mechanic Male"},
        {"g_m_y_mexgang_01","Cartel Male"},
        {"csb_ortega","Vagos Male"},
        {"u_m_y_rsranger_01","Ranger Mascot"},
        {"a_m_o_beach_01","Beach Old Man"},
        {"u_m_m_jewelsec_01","Security"},
        {"a_m_m_beach_01","Beach Random Male Black"},
        {"a_m_y_musclbeac_02","Beach Random Male"},
        {"s_m_y_garbage","Garbage Man"},
        {"csb_oscar","Mexican Male"},
        {"csb_trafficwarden","Traffic Warden"},
        {"s_m_m_janitor","Janitor"},
        {"a_m_m_soucent_01","a_m_m_soucent_01"},
        {"a_m_y_bevhills_02","a_m_y_bevhills_02"},
        {"g_m_m_armgoon_01","g_m_m_armgoon_01"},
        {"g_m_m_mexboss_02","g_m_m_mexboss_02"},
        {"s_m_m_postal_02","s_m_m_postal_02"},
        {"a_m_m_eastsa_02","a_m_m_eastsa_02"},
        {"a_m_o_soucent_03","a_m_o_soucent_03"},
        {"a_m_y_motox_02","a_m_y_motox_02"},
        {"a_m_m_eastsa_01","a_m_m_eastsa_01"},
        {"s_m_m_ups_02","s_m_m_ups_02"},
        {"a_m_y_juggalo_01","a_m_y_juggalo_01"},
        {"s_m_m_highsec_01","s_m_m_highsec_01"},
        {"a_m_y_bevhills_01","a_m_y_bevhills_01"},
        {"a_m_m_og_boss_01","a_m_m_og_boss_01"},
        {"a_m_y_business_03","a_m_y_business_03"},
        {"g_m_y_strpunk_01","g_m_y_strpunk_01"},
        {"s_m_m_migrant_01","s_m_m_migrant_01"},
        {"a_m_m_mexlabor_01","a_m_m_mexlabor_01"},
        {"a_m_m_tramp_01","a_m_m_tramp_01"},
        {"csb_car3guy1","csb_car3guy1"},
        {"a_m_y_yoga_01","a_m_y_yoga_01"},
        {"s_m_m_postal_01","s_m_m_postal_01"},
        {"a_m_y_methhead_01","a_m_y_methhead_01"},
        {"u_m_y_staggrm_01","u_m_y_staggrm_01"},
        {"g_m_y_ballaeast_01","g_m_y_ballaeast_01"},
        {"s_m_y_dwservice_01","s_m_y_dwservice_01"},
        {"a_m_y_mexthug_01","a_m_y_mexthug_01"},
        {"a_m_m_hasjew_01","a_m_m_hasjew_01"},
        {"a_m_y_eastsa_01","a_m_y_eastsa_01"},
        {"g_m_y_ballaorig_01","g_m_y_ballaorig_01"},
        {"a_m_y_sunbathe_01","a_m_y_sunbathe_01"},
        {"a_m_y_hasjew_01","a_m_y_hasjew_01"},
        {"a_m_y_golfer_01","a_m_y_golfer_01"},
        {"a_m_y_vindouche_01","a_m_y_vindouche_01"},
        {"g_m_m_chigoon_01","g_m_m_chigoon_01"},
        {"a_m_y_beachvesp_01","a_m_y_beachvesp_01"},
        {"a_m_m_salton_02","a_m_m_salton_02"},
        {"a_m_m_soucent_02","a_m_m_soucent_02"},
        {"u_m_y_tattoo_01","u_m_y_tattoo_01"},
        {"a_m_m_beach_02","a_m_m_beach_02"},
        {"s_m_y_strvend_01","s_m_y_strvend_01"},
        {"u_m_y_sbike","u_m_y_sbike"},
        {"g_m_y_salvagoon_03","g_m_y_salvagoon_03"},
        {"g_m_y_famdnf_01","g_m_y_famdnf_01"},
        {"u_m_m_markfost","u_m_m_markfost"},
        {"a_m_y_runner_01","a_m_y_runner_01"},
        {"g_m_m_chemwork_01","g_m_m_chemwork_01"},
        {"s_m_m_doctor_01","s_m_m_doctor_01"},
        {"a_m_y_hippy_01","a_m_y_hippy_01"},
        {"a_m_m_genfat_02","a_m_m_genfat_02"},
        {"a_m_y_gay_01","a_m_y_gay_01"},
        {"a_m_y_cyclist_01","a_m_y_cyclist_01"},
        {"u_m_y_pogo_01","u_m_y_pogo_01"},
        {"s_m_y_factory_01","s_m_y_factory_01"},
        {"s_m_m_ammucountry","s_m_m_ammucountry"},
        {"a_m_y_breakdance_01","a_m_y_breakdance_01"},
        {"a_m_y_soucent_02","a_m_y_soucent_02"},
        {"u_m_m_willyfist","u_m_m_willyfist"},
        {"a_m_y_business_02","a_m_y_business_02"},
        {"s_m_y_busboy_01","s_m_y_busboy_01"},
        {"a_m_y_hipster_03","a_m_y_hipster_03"},
        {"csb_g","csb_g"},
        {"a_m_y_busicas_01","a_m_y_busicas_01"},
        {"s_m_m_pilot_02","s_m_m_pilot_02"},
        {"g_m_m_korboss_01","g_m_m_korboss_01"},
        {"s_m_m_cntrybar_01","s_m_m_cntrybar_01"},
        {"a_m_y_business_01","a_m_y_business_01"},
        {"csb_grove_str_dlr","csb_grove_str_dlr"},
        {"a_m_m_bevhills_01","a_m_m_bevhills_01"},
        {"u_m_y_cyclist_01","u_m_y_cyclist_01"},
        {"a_m_m_mexcntry_01","a_m_m_mexcntry_01"},
        {"u_m_y_proldriver_01","u_m_y_proldriver_01"},
        {"csb_janitor","csb_janitor"},
        {"a_m_y_hiker_01","a_m_y_hiker_01"},
        {"u_m_y_party_01","u_m_y_party_01"},
        {"g_m_y_korean_01","g_m_y_korean_01"},
        {"a_m_y_beach_01","a_m_y_beach_01"},
        {"u_m_y_paparazzi","u_m_y_paparazzi"},
        {"a_m_o_salton_01","a_m_o_salton_01"},
        {"u_m_y_militarybum","u_m_y_militarybum"},
        {"g_m_y_salvagoon_02","g_m_y_salvagoon_02"},
        {"a_m_m_salton_01","a_m_m_salton_01"},
        {"a_m_y_runner_02","a_m_y_runner_02"},
        {"csb_ramp_mex","csb_ramp_mex"},
        {"csb_car3guy2","csb_car3guy2"},
        {"u_m_y_imporage","u_m_y_imporage"},
        {"s_m_m_strpreach_01","s_m_m_strpreach_01"},
        {"u_m_y_gunvend_01","u_m_y_gunvend_01"},
        {"s_m_m_strperf_01","s_m_m_strperf_01"},
        {"a_m_y_stwhi_02","a_m_y_stwhi_02"},
        {"a_m_y_vinewood_03","a_m_y_vinewood_03"},
        {"a_m_y_skater_02","a_m_y_skater_02"},
        {"a_m_y_skater_01","a_m_y_skater_01"},
        {"u_m_y_fibmugger_01","u_m_y_fibmugger_01"},
        {"s_m_y_pilot_01","s_m_y_pilot_01"},
        {"u_m_y_burgerdrug_01","u_m_y_burgerdrug_01"},
        {"u_m_m_jewelthief","u_m_m_jewelthief"},
        {"a_m_y_stlat_01","a_m_y_stlat_01"},
        {"a_m_m_malibu_01","a_m_m_malibu_01"},
        {"a_m_m_genfat_01","a_m_m_genfat_01"},
        {"a_m_m_bevhills_02","a_m_m_bevhills_02"},
        {"a_m_y_epsilon_01","a_m_y_epsilon_01"},
        {"u_m_y_antonb","u_m_y_antonb"},
        {"u_m_y_abner","u_m_y_abner"},
        {"u_m_m_partytarget","u_m_m_partytarget"},
        {"u_m_o_tramp_01","u_m_o_tramp_01"},
        {"s_m_m_pilot_01","s_m_m_pilot_01"},
        {"u_m_o_finguru_01","u_m_o_finguru_01"},
        {"u_m_m_spyactor","u_m_m_spyactor"},
        {"u_m_m_rivalpap","u_m_m_rivalpap"},
        {"g_m_y_lost_01","g_m_y_lost_01"},
        {"u_m_m_jesus_01","u_m_m_jesus_01"},
        {"u_m_m_griff_01","u_m_m_griff_01"},
        {"u_m_m_glenstank_01","u_m_m_glenstank_01"},
        {"s_m_m_hairdress_01","s_m_m_hairdress_01"},
        {"s_m_m_strvend_01","s_m_m_strvend_01"},
        {"u_m_m_fibarchitect","u_m_m_fibarchitect"},
        {"u_m_m_bikehire_01","u_m_m_bikehire_01"},
        {"u_m_m_aldinapoli","u_m_m_aldinapoli"},
        {"g_m_m_mexboss_01","g_m_m_mexboss_01"},
        {"s_m_m_gentransport","s_m_m_gentransport"},
        {"a_m_y_soucent_04","a_m_y_soucent_04"},
        {"s_m_y_winclean_01","s_m_y_winclean_01"},
        {"csb_ballasog","csb_ballasog"},
        {"a_m_y_dhill_01","a_m_y_dhill_01"},
        {"csb_prologuedriver","csb_prologuedriver"},
        {"s_m_y_waiter_01","s_m_y_waiter_01"},
        {"g_m_y_armgoon_02","g_m_y_armgoon_02"},
        {"s_m_y_valet_01","s_m_y_valet_01"},
        {"g_m_y_strpunk_02","g_m_y_strpunk_02"},
        {"s_m_y_shop_mask","s_m_y_shop_mask"},
        {"s_m_m_lifeinvad_01","s_m_m_lifeinvad_01"},
        {"s_m_y_robber_01","s_m_y_robber_01"},
        {"s_m_y_prisoner_01","s_m_y_prisoner_01"},
        {"u_m_y_chip","u_m_y_chip"},
        {"s_m_y_mime","s_m_y_mime"},
        {"csb_hao","csb_hao"},
        {"a_m_y_stbla_02","a_m_y_stbla_02"},
        {"a_m_y_ktown_02","a_m_y_ktown_02"},
        {"s_m_y_dwservice_02","s_m_y_dwservice_02"},
        {"s_m_y_dockwork_01","s_m_y_dockwork_01"},
        {"s_m_y_ammucity_01","s_m_y_ammucity_01"},
        {"a_m_y_soucent_01","a_m_y_soucent_01"},
        {"a_m_y_vinewood_04","a_m_y_vinewood_04"},
        {"s_m_y_dealer_01","s_m_y_dealer_01"},
        {"a_m_m_skidrow_01","a_m_m_skidrow_01"},
        {"s_m_y_construct_02","s_m_y_construct_02"},
        {"a_m_m_ktown_01","a_m_m_ktown_01"},
        {"g_m_y_famca_01","g_m_y_famca_01"},
        {"s_m_y_construct_01","s_m_y_construct_01"},
        {"s_m_y_clown_01","s_m_y_clown_01"},
        {"a_m_m_stlat_02","a_m_m_stlat_02"},
        {"a_m_o_genstreet_01","a_m_o_genstreet_01"},
        {"csb_chef","csb_chef"},
        {"s_m_y_baywatch_01","s_m_y_baywatch_01"},
        {"s_m_y_armymech_01","s_m_y_armymech_01"},
        {"s_m_y_devinsec_01","s_m_y_devinsec_01"},
        {"a_m_m_paparazzi_01","a_m_m_paparazzi_01"},
        {"s_m_m_scientist_01","s_m_m_scientist_01"},
        {"s_m_m_ups_01","s_m_m_ups_01"},
        {"a_m_y_roadcyc_01","a_m_y_roadcyc_01"},
        {"csb_reporter","csb_reporter"},
        {"u_m_y_hippie_01","u_m_y_hippie_01"},
        {"csb_ramp_hic","csb_ramp_hic"},
        {"a_m_m_soucent_04","a_m_m_soucent_04"},
        {"s_m_m_movspace_01","s_m_m_movspace_01"},
        {"a_m_m_socenlat_01","a_m_m_socenlat_01"},
        {"g_m_y_korean_02","g_m_y_korean_02"},
        {"a_m_y_hipster_02","a_m_y_hipster_02"},
        {"s_m_m_lsmetro_01","s_m_m_lsmetro_01"},
        {"a_m_m_fatlatin_01","a_m_m_fatlatin_01"},
        {"s_m_m_linecook","s_m_m_linecook"},
        {"a_m_y_beach_02","a_m_y_beach_02"},
        {"s_m_m_lathandy_01","s_m_m_lathandy_01"},
        {"a_m_y_polynesian_01","a_m_y_polynesian_01"},
        {"a_m_y_acult_02","a_m_y_acult_02"},
        {"s_m_m_highsec_02","s_m_m_highsec_02"},
        {"g_m_m_chicold_01","g_m_m_chicold_01"},
        {"u_m_m_filmdirector","u_m_m_filmdirector"},
        {"s_m_y_xmech_02","s_m_y_xmech_02"},
        {"s_m_m_gardener_01","s_m_m_gardener_01"},
        {"a_m_y_latino_01","a_m_y_latino_01"},
        {"s_m_m_gaffer_01","s_m_m_gaffer_01"},
        {"s_m_m_fiboffice_02","s_m_m_fiboffice_02"},
        {"a_m_y_stbla_01","a_m_y_stbla_01"},
        {"s_m_m_dockwork_01","s_m_m_dockwork_01"},
        {"a_m_y_downtown_01","a_m_y_downtown_01"},
        {"csb_ramp_hipster","csb_ramp_hipster"},
        {"a_m_m_hillbilly_02","a_m_m_hillbilly_02"},
        {"a_m_y_ktown_01","a_m_y_ktown_01"},
        {"s_m_m_ciasec_01","s_m_m_ciasec_01"},
        {"s_m_m_bouncer_01","s_m_m_bouncer_01"},
        {"a_m_m_hillbilly_01","a_m_m_hillbilly_01"},
        {"a_m_m_tourist_01","a_m_m_tourist_01"},
        {"s_m_m_autoshop_02","s_m_m_autoshop_02"},
        {"a_m_y_motox_01","a_m_y_motox_01"},
        {"a_m_y_gay_02","a_m_y_gay_02"},
        {"s_m_m_autoshop_01","s_m_m_autoshop_01"},
        {"a_m_y_beach_03","a_m_y_beach_03"},
        {"g_m_y_lost_02","g_m_y_lost_02"},
        {"s_m_y_chef_01","s_m_y_chef_01"},
        {"a_m_y_salton_01","a_m_y_salton_01"},
        {"a_m_m_skater_01","a_m_m_skater_01"},
        {"g_m_y_lost_03","g_m_y_lost_03"},
        {"g_m_y_salvaboss_01","g_m_y_salvaboss_01"},
        {"a_m_o_tramp_01","a_m_o_tramp_01"},
        {"g_m_y_pologoon_01","g_m_y_pologoon_01"},
        {"csb_ramp_gang","csb_ramp_gang"},
        {"a_m_y_genstreet_01","a_m_y_genstreet_01"},
        {"g_m_y_salvagoon_01","g_m_y_salvagoon_01"},
        {"csb_chin_goon","csb_chin_goon"},
        {"a_m_m_salton_04","a_m_m_salton_04"},
        {"g_m_y_mexgoon_02","g_m_y_mexgoon_02"},
        {"g_m_y_mexgoon_01","g_m_y_mexgoon_01"},
        {"a_m_o_soucent_02","a_m_o_soucent_02"},
        {"a_m_m_tranvest_01","a_m_m_tranvest_01"},
        {"csb_anton","csb_anton"},
        {"g_m_y_korlieut_01","g_m_y_korlieut_01"},
        {"a_m_m_tranvest_02","a_m_m_tranvest_02"},
        {"a_m_m_indian_01","a_m_m_indian_01"},
        {"csb_roccopelosi","csb_roccopelosi"},
        {"a_m_o_soucent_01","a_m_o_soucent_01"},
        {"a_m_y_genstreet_02","a_m_y_genstreet_02"},
        {"s_m_m_mariachi_01","s_m_m_mariachi_01"},
        {"a_m_o_acult_02","a_m_o_acult_02"},
        {"g_m_m_armlieut_01","g_m_m_armlieut_01"},
        {"s_m_y_grip_01","s_m_y_grip_01"},
        {"u_m_y_prisoner_01","u_m_y_prisoner_01"},
        {"a_m_y_beachvesp_02","a_m_y_beachvesp_02"},
        {"g_m_y_ballasout_01","g_m_y_ballasout_01"},
        {"a_m_y_vinewood_01","a_m_y_vinewood_01"},
        {"a_m_m_business_01","a_m_m_business_01"},
        {"g_m_m_chigoon_02","g_m_m_chigoon_02"},
        {"csb_hugh","csb_hugh"},
        {"a_m_o_ktown_01","a_m_o_ktown_01"},
        {"a_m_y_soucent_03","a_m_y_soucent_03"},
        {"csb_customer","csb_customer"},
        {"g_m_y_pologoon_02","g_m_y_pologoon_02"},
        {"a_m_m_soucent_03","a_m_m_soucent_03"},
        {"a_m_y_epsilon_02","a_m_y_epsilon_02"},
        {"a_m_y_indian_01","a_m_y_indian_01"},
        {"a_m_y_hipster_01","a_m_y_hipster_01"},
        {"a_m_m_tennis_01","a_m_m_tennis_01"},
        {"u_m_y_baygor","u_m_y_baygor"},
        {"u_m_y_babyd","u_m_y_babyd"},
        {"u_m_y_guido_01","u_m_y_guido_01"},
        {"s_m_m_trucker_01","s_m_m_trucker_01"},
        {"csb_cletus","csb_cletus"},
        {"csb_burgerdrug","csb_burgerdrug"},
        {"a_m_m_rurmeth_01","a_m_m_rurmeth_01"},
        {"a_m_y_stwhi_01","a_m_y_stwhi_01"},
        {"a_f_y_vinewood_04","a_f_y_vinewood_04"},
        {"u_f_o_moviestar","u_f_o_moviestar"},
        {"a_f_m_bevhills_02","a_f_m_bevhills_02"},
        {"u_f_m_miranda","u_f_m_miranda"},
        {"csb_screen_writer","csb_screen_writer"},
        {"csb_maude","csb_maude"},
        {"u_f_y_comjane","u_f_y_comjane"},
        {"csb_anita","csb_anita"},
        {"a_f_y_soucent_02","a_f_y_soucent_02"},
        {"u_f_y_princess","u_f_y_princess"},
        {"a_f_y_eastsa_01","a_f_y_eastsa_01"},
        {"a_f_o_ktown_01","a_f_o_ktown_01"},
        {"a_f_m_fatwhite_01","a_f_m_fatwhite_01"},
        {"a_f_y_hipster_03","a_f_y_hipster_03"},
        {"a_f_y_vinewood_03","a_f_y_vinewood_03"},
        {"a_f_y_epsilon_01","a_f_y_epsilon_01"},
        {"s_f_y_migrant_01","s_f_y_migrant_01"},
        {"a_f_y_hipster_01","a_f_y_hipster_01"},
        {"a_f_y_business_03","a_f_y_business_03"},
        {"g_f_y_ballas_01","g_f_y_ballas_01"},
        {"a_f_o_soucent_02","a_f_o_soucent_02"},
        {"a_f_m_eastsa_02","a_f_m_eastsa_02"},
        {"a_f_y_bevhills_04","a_f_y_bevhills_04"},
        {"s_f_y_bartender_01","s_f_y_bartender_01"},
        {"a_f_m_soucentmc_01","a_f_m_soucentmc_01"},
        {"a_f_m_fatcult_01","a_f_m_fatcult_01"},
        {"u_f_y_bikerchic","u_f_y_bikerchic"},
        {"a_f_y_hippie_01","a_f_y_hippie_01"},
        {"a_f_y_vinewood_02","a_f_y_vinewood_02"},
        {"a_f_m_eastsa_01","a_f_m_eastsa_01"},
        {"a_f_y_golfer_01","a_f_y_golfer_01"},
        {"s_f_y_factory_01","s_f_y_factory_01"},
        {"s_f_m_shop_high","s_f_m_shop_high"},
        {"s_f_y_sweatshop_01","s_f_y_sweatshop_01"},
        {"s_f_m_sweatshop_01","s_f_m_sweatshop_01"},
        {"a_f_y_topless_01","a_f_y_topless_01"},
        {"a_f_y_genhot_01","a_f_y_genhot_01"},
        {"a_f_y_hipster_02","a_f_y_hipster_02"},
        {"a_f_y_scdressy_01","a_f_y_scdressy_01"},
        {"a_f_y_hipster_04","a_f_y_hipster_04"},
        {"a_f_m_bevhills_01","a_f_m_bevhills_01"},
        {"a_f_y_tourist_01","a_f_y_tourist_01"},
        {"a_f_y_business_01","a_f_y_business_01"},
        {"a_f_m_downtown_01","a_f_m_downtown_01"},
        {"a_f_m_skidrow_01","a_f_m_skidrow_01"},
        {"a_f_m_business_02","a_f_m_business_02"},
        {"a_f_m_salton_01","a_f_m_salton_01"},
        {"s_f_y_stripper_01","s_f_y_stripper_01"},
        {"a_f_y_juggalo_01","a_f_y_juggalo_01"},
        {"s_f_y_movprem_01","s_f_y_movprem_01"},
        {"s_f_y_hooker_01","s_f_y_hooker_01"},
        {"u_f_m_promourn_01","u_f_m_promourn_01"},
        {"a_f_m_trampbeac_01","a_f_m_trampbeac_01"},
        {"a_f_y_vinewood_01","a_f_y_vinewood_01"},
        {"a_f_o_salton_01","a_f_o_salton_01"},
        {"u_f_y_poppymich","u_f_y_poppymich"},
        {"a_f_m_bodybuild_01","a_f_m_bodybuild_01"},
        {"a_f_y_business_02","a_f_y_business_02"},
        {"a_f_m_ktown_02","a_f_m_ktown_02"},
        {"a_f_y_fitness_02","a_f_y_fitness_02"},
        {"a_f_y_skater_01","a_f_y_skater_01"},
        {"u_f_m_corpse_01","u_f_m_corpse_01"},
        {"a_f_m_fatbla_01","a_f_m_fatbla_01"},
        {"a_f_y_bevhills_02","a_f_y_bevhills_02"},
        {"a_f_m_tramp_01","a_f_m_tramp_01"},
        {"s_f_y_baywatch_01","s_f_y_baywatch_01"},
        {"g_f_y_families_01","g_f_y_families_01"},
        {"a_f_y_soucent_03","a_f_y_soucent_03"},
        {"a_f_y_eastsa_02","a_f_y_eastsa_02"},
        {"u_f_o_prolhost_01","u_f_o_prolhost_01"},
        {"a_f_y_rurmeth_01","a_f_y_rurmeth_01"},
        {"csb_tonya","csb_tonya"},
        {"csb_denise_friend","csb_denise_friend"},
        {"g_f_y_lost_01","g_f_y_lost_01"},
        {"a_f_y_yoga_01","a_f_y_yoga_01"},
        {"u_f_y_spyactress","u_f_y_spyactress"},
        {"u_f_y_mistress","u_f_y_mistress"},
        {"u_f_y_jewelass_01","u_f_y_jewelass_01"},
        {"a_f_o_soucent_01","a_f_o_soucent_01"},
        {"u_f_y_hotposh_01","u_f_y_hotposh_01"},
        {"a_f_y_soucent_01","a_f_y_soucent_01"},
        {"a_f_y_bevhills_01","a_f_y_bevhills_01"},
        {"a_f_y_indian_01","a_f_y_indian_01"},
        {"a_f_y_eastsa_03","a_f_y_eastsa_03"},
        {"a_f_m_ktown_01","a_f_m_ktown_01"},
        {"a_f_m_beach_01","a_f_m_beach_01"},
        {"s_f_y_stripper_02","s_f_y_stripper_02"},
        {"s_f_y_stripperlite","s_f_y_stripperlite"},
        {"s_f_y_shop_low","s_f_y_shop_low"},
        {"s_f_m_fembarber","s_f_m_fembarber"},
        {"s_f_y_hooker_03","s_f_y_hooker_03"},
        {"s_f_y_hooker_02","s_f_y_hooker_02"},
        {"a_f_o_indian_01","a_f_o_indian_01"},
        {"a_f_y_beach_01","a_f_y_beach_01"},
        {"a_f_o_genstreet_01","a_f_o_genstreet_01"},
        {"csb_stripper_01","csb_stripper_01"},
        {"a_f_m_prolhost_01","a_f_m_prolhost_01"},
        {"a_f_y_hiker_01","a_f_y_hiker_01"},
        {"csb_abigail","csb_abigail"},
        {"a_f_m_soucent_01","a_f_m_soucent_01"},
        {"s_f_y_shop_mid","s_f_y_shop_mid"},
        {"a_f_y_runner_01","a_f_y_runner_01"},
        {"a_f_y_bevhills_03","a_f_y_bevhills_03"},
        {"s_f_y_airhostess_01","s_f_y_airhostess_01"},
        {"s_f_m_maid_01","s_f_m_maid_01"},
        {"a_f_m_tourist_01","a_f_m_tourist_01"},
        {"a_f_y_tennis_01","a_f_y_tennis_01"},
        {"csb_stripper_02","csb_stripper_02"},
        {"g_f_y_vagos_01","g_f_y_vagos_01"},
        {"a_f_y_tourist_02","a_f_y_tourist_02"},
        {"a_f_m_soucent_02","a_f_m_soucent_02"},
        {"a_f_y_business_04","a_f_y_business_04"},
        {"a_f_y_fitness_01","a_f_y_fitness_01"},
        {"mp_g_m_pros_01","mp_g_m_pros_01"},
        {"mp_m_shopkeep_01","mp_m_shopkeep_01"},
        {"mp_m_exarmy_01","mp_m_exarmy_01"},
    },
    ["admin"] = {
        ["config"] = {"Admin Peds", permissions = {"player.group.add"}},
        {"a_c_rottweiler", "Dog 1"},
        {"a_c_shepherd", "Dog 2"},
        {"a_c_rhesus", "Dog 3"},
        {"a_c_chop", "Dog 4"},
    },
    ["aa"] = {
        ["config"] = {"AA Peds", permissions = {}},
        {"s_m_m_lathandy_01", "AA Mechanic"},
        {"mp_m_freemode_01", "Citizen"}
    },
    ["Casino"] = {
        ["config"] = {name = "Casino Peds", permissions = {"casino.whitelisted"}},
        {"ig_tomcasino", "Casino Owner"},
        {"s_m_y_westsec_01", "Casino Security"},
        {"u_f_m_casinocash_01", "Casino Staff 1"},
        {"s_m_y_casino_01", "Casino Staff 2"},
        {"s_f_y_casino_01", "Casino Staff Female"},
    },
    ["Rebel"] = {
        ["config"] = {name = "Rebel Peds", permissions = {"rebellicense.whitelisted"}},
        {"rebel_09","Rebel 9"},
        {"rebel_10","Rebel 10"},
        {"rebel_11","Rebel 11"},
    },
}

cfg.pedMenus = {
    {"admin", vector3(54.124324798584, 7244.4296875, 2.3570654392242)},
    {"Normal", vector3(71.812164306641,-1391.7836914063,29.376153945923)},
    {"Normal", vector3(-706.46051025391,-151.13081359863,37.415134429932)},
    {"Normal", vector3(429.30685424805,-807.82000732422,29.491151809692)},
    {"Normal", vector3(-822.35620117188,-1069.5296630859,11.328113555908)},
    {"Normal", vector3(-1181.8049316406,-764.53973388672,17.326150894165)},
    {"Normal", vector3(-1447.1085205078,-240.33535766602,49.819042205811)},
    {"Normal", vector3(6.5127530097961,6508.82421875,31.877857208252)},
    {"Normal", vector3(1697.9753417969,4821.1333007813,42.063133239746)},
    {"Normal", vector3(117.7219543457,-233.36813354492,54.55782699585)},
    {"Normal", vector3(617.30517578125,2775.0363769531,42.08810043335)},
    {"Normal", vector3(1197.654296875,2713.5983886719,38.222648620605)},
    {"Normal", vector3(-3178.5476074219,1035.8984375,20.863212585449)},

    --Rebel
    {"Rebel", vector3(1421.1374511719,6332.224609375,23.865062713623)},

    --Casino
    {"Casino", vector3(932.96649169922,14.533226013184,81.106109619141)},

    --AA
    {"aa", vector3(398.4326171875, -1634.4913330078, 29.291942596436)},
}

return cfg

