--[[
    BEGINNER GUIDE — Chatminievents
    ===============================

    File: cmg/prod/cfg/cfg_chatminievents.lua
    Purpose: This file contains configuration/data.

    How to read FiveM Lua:
      * RegisterNetEvent/AddEventHandler = code that runs when an event happens.
      * TriggerServerEvent = this client asks/tells the server to do something.
      * PlayerPedId() = your local GTA character (called a 'ped').
      * vector3/vector4 = world coordinates; vector4 also normally includes heading.
      * RageUI/NUI = menu or browser-based UI code.
      * CreateThread/Wait = code that can keep running without freezing the game.

]]
local cfg = {}

cfg.reverseWords = {
	"balance",
	"capture",
	"channel",
	"cluster",
	"compact",
	"cricket",
	"deposit",
	"dynamic",
	"elastic",
	"faction",
	"gateway",
	"harvest",
	"insight",
	"journey",
	"kitchen",
	"lantern",
	"magnetic",
	"network",
	"organic",
	"package",
	"quantum",
	"railway",
	"shelter",
	"traffic",
	"uniform",
	"venture",
	"whistle",
	"zealous",
}

cfg.letterCountWords = {
	"elephant",
	"mississippi",
	"committee",
	"bookkeeper",
	"successful",
	"environment",
	"opportunity",
	"recommendation",
	"development",
	"communication",
	"abbreviation",
	"assassination",
	"entertainment",
	"infrastructure",
	"responsibility",
	"accommodation",
	"aggression",
	"apparatus",
	"assessment",
	"assignment",
	"attendance",
	"balloon",
	"broccoli",
	"business",
	"camouflage",
	"characteristic",
	"collaboration",
	"concession",
	"conscientious",
	"embarrassment",
	"exaggeration",
	"fluorescence",
	"harassment",
	"illumination",
	"inauguration",
	"intelligence",
	"interruption",
	"kindergarten",
	"memorandum",
	"millennium",
	"occurrence",
	"parallel",
	"personnel",
	"possession",
	"pronunciation",
	"succession",
	"surveillance",
	"unnecessary",
	"vacuum",
	"vocabulary",
	"watermelon",
	"cocoon",
	"coffee",
	"common",
	"courier",
	"express",
	"football",
	"glamorous",
	"grammar",
	"hammer",
	"hollow",
	"immediate",
	"innumerable",
	"letter",
	"little",
	"mammoth",
	"occasion",
	"programming",
	"scatter",
	"scissors",
	"serendipity",
	"shimmer",
	"skeleton",
	"slippery",
	"squirrel",
	"success",
	"summation",
	"symmetrical",
	"tattoo",
	"terrific",
	"turbulence",
	"umbrella",
	"vanilla",
	"vegetarian",
	"wellness",
}

-- Lesser-known capitals and countries where the obvious city is wrong.
cfg.capitalCities = {
	{ country = "Australia", answers = { "canberra" } },
	{ country = "Turkey", answers = { "ankara" } },
	{ country = "Brazil", answers = { "brasilia" } },
	{ country = "Canada", answers = { "ottawa" } },
	{ country = "Switzerland", answers = { "bern", "berne" } },
	{ country = "New Zealand", answers = { "wellington" } },
	{ country = "Morocco", answers = { "rabat" } },
	{ country = "Nigeria", answers = { "abuja" } },
	{ country = "Pakistan", answers = { "islamabad" } },
	{ country = "Myanmar", answers = { "naypyidaw" } },
	{ country = "Tanzania", answers = { "dodoma" } },
	{ country = "Ivory Coast", answers = { "yamoussoukro" } },
	{ country = "Kazakhstan", answers = { "astana", "nur-sultan" } },
	{ country = "Mongolia", answers = { "ulaanbaatar", "ulan bator" } },
	{ country = "Bhutan", answers = { "thimphu" } },
	{ country = "Iceland", answers = { "reykjavik" } },
	{ country = "Madagascar", answers = { "antananarivo" } },
	{ country = "Burkina Faso", answers = { "ouagadougou" } },
	{ country = "Namibia", answers = { "windhoek" } },
	{ country = "Botswana", answers = { "gaborone" } },
	{ country = "Lesotho", answers = { "maseru" } },
	{ country = "Eswatini", answers = { "mbabane" } },
	{ country = "Belize", answers = { "belmopan" } },
	{ country = "Vietnam", answers = { "hanoi" } },
	{ country = "Sri Lanka", answers = { "sri jayawardenepura kotte", "sri jayewardenepura kotte" } },
	{ country = "Chad", answers = { "n'djamena", "ndjamena" } },
	{ country = "Eritrea", answers = { "asmara" } },
	{ country = "Guyana", answers = { "georgetown" } },
	{ country = "Suriname", answers = { "paramaribo" } },
	{ country = "Paraguay", answers = { "asuncion" } },
	{ country = "Uruguay", answers = { "montevideo" } },
	{ country = "Ecuador", answers = { "quito" } },
	{ country = "Costa Rica", answers = { "san jose" } },
	{ country = "El Salvador", answers = { "san salvador" } },
	{ country = "Honduras", answers = { "tegucigalpa" } },
	{ country = "Nicaragua", answers = { "managua" } },
	{ country = "Cuba", answers = { "havana" } },
	{ country = "Jamaica", answers = { "kingston" } },
	{ country = "Haiti", answers = { "port-au-prince", "port au prince" } },
	{ country = "Dominican Republic", answers = { "santo domingo" } },
	{ country = "Panama", answers = { "panama city", "panama" } },
	{ country = "Guatemala", answers = { "guatemala city", "guatemala" } },
	{ country = "Armenia", answers = { "yerevan" } },
	{ country = "Georgia", answers = { "tbilisi" } },
	{ country = "Azerbaijan", answers = { "baku" } },
	{ country = "Uzbekistan", answers = { "tashkent" } },
	{ country = "Kyrgyzstan", answers = { "bishkek" } },
	{ country = "Tajikistan", answers = { "dushanbe" } },
	{ country = "Turkmenistan", answers = { "ashgabat" } },
	{ country = "Senegal", answers = { "dakar" } },
	{ country = "Mali", answers = { "bamako" } },
	{ country = "Mozambique", answers = { "maputo" } },
	{ country = "Malawi", answers = { "lilongwe" } },
	{ country = "Zambia", answers = { "lusaka" } },
	{ country = "Zimbabwe", answers = { "harare" } },
	{ country = "Rwanda", answers = { "kigali" } },
	{ country = "Burundi", answers = { "gitega" } },
	{ country = "Albania", answers = { "tirana" } },
	{ country = "North Macedonia", answers = { "skopje" } },
	{ country = "Kosovo", answers = { "pristina" } },
	{ country = "Montenegro", answers = { "podgorica" } },
	{ country = "Serbia", answers = { "belgrade" } },
	{ country = "Croatia", answers = { "zagreb" } },
	{ country = "Slovenia", answers = { "ljubljana" } },
	{ country = "Slovakia", answers = { "bratislava" } },
	{ country = "Latvia", answers = { "riga" } },
	{ country = "Lithuania", answers = { "vilnius" } },
	{ country = "Estonia", answers = { "tallinn" } },
	{ country = "Belarus", answers = { "minsk" } },
	{ country = "Moldova", answers = { "chisinau" } },
	{ country = "Cyprus", answers = { "nicosia" } },
	{ country = "Malta", answers = { "valletta" } },
	{ country = "Luxembourg", answers = { "luxembourg", "luxembourg city" } },
}

return cfg
