-- cfg/cfg_food.lua
local cfg = {}

cfg.food = {
    burger = {
        props = { "burger1", "burger2", "burger3" },
        use = { res = "foodpack1", fn = "useBurger" },
        hunger = 50,
        hydration = 0,
    },
    hotdog = {
        props = { "hotdog1", "hotdog2", "hotdog3" },
        use = { res = "foodpack1", fn = "useHotdog" },
        hunger = 40,
        hydration = 0,
    },
    donuts = {
        props = { "donuts1", "donuts2", "donuts3" },
        use = { res = "foodpack1", fn = "useDonuts" },
        hunger = 30,
        hydration = 0,
    },
    pizza = {
        props = { "pizza1", "pizza2", "pizza3" },
        use = { res = "foodpack1", fn = "usePizza" },
        hunger = 50,
        hydration = 0,
    },
    noodles_box = {
        props = { "noodles", "box", "chopsticks", "noodleschopstick" },
        use = { res = "foodpack1", fn = "useNoodlesbox" },
        hunger = 60,
        hydration = 0,
    },
    pasta_box = {
        props = { "pasta", "boxpasta", "prop_cs_fork", "pastafork" },
        use = { res = "foodpack1", fn = "usePastabox" },
        hunger = 70,
        hydration = 0,
    },
    ecola = {
        props = { "ng_proc_sodacan_01a" },
        use = { res = "foodpack1", fn = "useSodaCan" },
        hunger = 10,
        hydration = 30,
    },
    sprunk = {
        props = { "ng_proc_sodacan_01b" },
        use = { res = "foodpack1", fn = "useSodaCan2" },
        hunger = 1,
        hydration = 30,
    },
    daiquiri = {
        props = { "prop_daiquiri" },
        use = { res = "foodpack1", fn = "useDaiquiri" },
        hunger = 0,
        hydration = 25,
    },
    mojito = {
        props = { "prop_mojito" },
        use = { res = "foodpack1", fn = "useMojito" },
        hunger = 0,
        hydration = 25,
    },
}

-- Merge vending machine consumables (vending items with eat/drink anim)
local vendingFood = {
    coffee = { hunger = 0, hydration = 20, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_c" }, prop = { model = "p_amb_coffeecup_01", bone = 28422, pos = vec3(0.0, 0.0, 0.0), rot = vec3(0.0, 0.0, 0.0) }, usetime = 6500 } },
    chips_cheese = { hunger = 20, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_chips1", bone = 57005, pos = vec3(0.16, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 6500 } },
    chips_paprika = { hunger = 20, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_chips2", bone = 57005, pos = vec3(0.16, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 6500 } },
    chips_ribs = { hunger = 20, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_chips3", bone = 57005, pos = vec3(0.16, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 6500 } },
    chips_salt = { hunger = 20, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_chips4", bone = 57005, pos = vec3(0.16, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 6500 } },
    chips_supersalt = { hunger = 20, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_chips5", bone = 57005, pos = vec3(0.16, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 6500 } },
    chips_habanero = { hunger = 20, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_chips6", bone = 57005, pos = vec3(0.16, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 6500 } },
    chocolate_meteorite = { hunger = 20, hydration = 0, vending = { anim = { dict = "mp_player_inteat@burger", clip = "mp_player_int_eat_burger_fp" }, prop = { model = "mxc_vend_prop_item_chocolate1", bone = 18905, pos = vec3(0.12, 0.04, 0.01), rot = vec3(51.55, -47.5, -4.65) }, usetime = 2500 } },
    chocolate_captain = { hunger = 20, hydration = 0, vending = { anim = { dict = "mp_player_inteat@burger", clip = "mp_player_int_eat_burger_fp" }, prop = { model = "mxc_vend_prop_item_chocolate2", bone = 18905, pos = vec3(0.12, 0.04, 0.01), rot = vec3(51.55, -47.5, -4.65) }, usetime = 2500 } },
    candy_zebra = { hunger = 20, hydration = 0, vending = { anim = { dict = "mp_player_inteat@burger", clip = "mp_player_int_eat_burger_fp" }, prop = { model = "mxc_vend_prop_item_candybar1", bone = 18905, pos = vec3(0.12, 0.04, 0.01), rot = vec3(51.55, -47.5, -4.65) }, usetime = 2500 } },
    candy_psqs = { hunger = 20, hydration = 0, vending = { anim = { dict = "mp_player_inteat@pnq", clip = "loop" }, prop = { model = "mxc_vend_prop_item_candybar2", bone = 18905, pos = vec3(0.14, -0.02, 0.06), rot = vec3(65.76, -57.6, 2.8) }, usetime = 2500 } },
    gum_peppermint = { hunger = 10, hydration = 0, vending = { anim = { dict = "mp_player_inteat@pnq", clip = "loop" }, prop = { model = "mxc_vend_prop_item_gum1", bone = 18905, pos = vec3(0.14, -0.02, 0.06), rot = vec3(65.76, -57.6, 2.8) }, usetime = 2500 } },
    gum_cinnamon = { hunger = 10, hydration = 0, vending = { anim = { dict = "mp_player_inteat@pnq", clip = "loop" }, prop = { model = "mxc_vend_prop_item_gum2", bone = 18905, pos = vec3(0.14, -0.02, 0.06), rot = vec3(65.76, -57.6, 2.8) }, usetime = 2500 } },
    gum_spearmint = { hunger = 10, hydration = 0, vending = { anim = { dict = "mp_player_inteat@pnq", clip = "loop" }, prop = { model = "mxc_vend_prop_item_gum3", bone = 18905, pos = vec3(0.14, -0.02, 0.06), rot = vec3(65.76, -57.6, 2.8) }, usetime = 2500 } },
    medicine_laxmax = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_medical1", bone = 57005, pos = vec3(0.16, 0.01, -0.07), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 1500 } },
    medicine_alcopatch = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_medical2", bone = 57005, pos = vec3(0.16, 0.01, -0.07), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 1500 } },
    medicine_mollis = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_medical3", bone = 57005, pos = vec3(0.16, 0.01, -0.07), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 1500 } },
    medicine_betta = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_medical4", bone = 57005, pos = vec3(0.16, 0.01, -0.07), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 1500 } },
    bottle_cola = { hunger = 0, hydration = 30, vending = { anim = { dict = "mp_player_intdrink", clip = "loop_bottle" }, prop = { model = "mxc_vend_prop_item_bottle1", bone = 18905, pos = vec3(0.12, -0.03, 0.03), rot = vec3(-98.4, 0.0, -15.0) }, usetime = 2500 } },
    bottle_junk = { hunger = 0, hydration = 30, vending = { anim = { dict = "mp_player_intdrink", clip = "loop_bottle" }, prop = { model = "mxc_vend_prop_item_bottle2", bone = 18905, pos = vec3(0.12, -0.03, 0.03), rot = vec3(-98.4, 0.0, -15.0) }, usetime = 2500 } },
    bottle_orang = { hunger = 0, hydration = 30, vending = { anim = { dict = "mp_player_intdrink", clip = "loop_bottle" }, prop = { model = "mxc_vend_prop_item_bottle3", bone = 18905, pos = vec3(0.12, -0.03, 0.03), rot = vec3(-98.4, 0.0, -15.0) }, usetime = 2500 } },
    bottle_tonic = { hunger = 0, hydration = 30, vending = { anim = { dict = "mp_player_intdrink", clip = "loop_bottle" }, prop = { model = "mxc_vend_prop_item_bottle4", bone = 18905, pos = vec3(0.12, -0.03, 0.03), rot = vec3(-98.4, 0.0, -15.0) }, usetime = 2500 } },
    bottle_water = { hunger = 0, hydration = 30, vending = { anim = { dict = "mp_player_intdrink", clip = "loop_bottle" }, prop = { model = "mxc_vend_prop_item_bottle5", bone = 18905, pos = vec3(0.12, -0.03, 0.03), rot = vec3(-98.4, 0.0, -15.0) }, usetime = 2500 } },
    bottle_sprunk = { hunger = 0, hydration = 30, vending = { anim = { dict = "mp_player_intdrink", clip = "loop_bottle" }, prop = { model = "mxc_vend_prop_item_bottle6", bone = 18905, pos = vec3(0.12, -0.03, 0.03), rot = vec3(-98.4, 0.0, -15.0) }, usetime = 2500 } },
    can_cola = { hunger = 0, hydration = 30, props = { "ng_proc_sodacan_01a" }, use = { res = "foodpack1", fn = "useSodaCan" } },
    can_orang = { hunger = 0, hydration = 30, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_cansoda2", bone = 57005, pos = vec3(0.14, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 2500 } },
    can_junk = { hunger = 0, hydration = 30, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_cansoda3", bone = 57005, pos = vec3(0.14, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 2500 } },
    can_sprunk = { hunger = 0, hydration = 30, props = { "ng_proc_sodacan_01b" }, use = { res = "foodpack1", fn = "useSodaCan2" } },
    can_logger = { hunger = 0, hydration = 30, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_canbeer1", bone = 57005, pos = vec3(0.14, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 2500 } },
    can_blarneys = { hunger = 0, hydration = 30, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_canbeer2", bone = 57005, pos = vec3(0.14, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 2500 } },
    can_hoplivion = { hunger = 0, hydration = 30, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_canbeer3", bone = 57005, pos = vec3(0.14, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 2500 } },
    can_cerbeza = { hunger = 0, hydration = 30, vending = { anim = { dict = "amb@world_human_drinking@coffee@male@idle_a", clip = "idle_a" }, prop = { model = "mxc_vend_prop_item_canbeer4", bone = 57005, pos = vec3(0.14, 0.01, -0.04), rot = vec3(-64.96, 36.0, -3.0) }, usetime = 2500 } },
    cigs_redwood = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    cigs_redwood2 = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    cigs_debonaireb = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    cigs_debonaireg = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    cigs_cardiaque = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    cigs_69brand = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    cigs_cok = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    cigs_estancia = { hunger = 0, hydration = 0, vending = { anim = { dict = "amb@world_human_aa_smoke@male@idle_a", clip = "idle_c" }, prop = { model = "prop_cs_ciggy_01b", bone = 57005, pos = vec3(0.18, 0.02, 0.02), rot = vec3(0, 103.42, 0) }, usetime = 10000 } },
    water = { hunger = 0, hydration = 30},
    condom = { hunger = 0, hydration = 0 },
    svapo_evape_box = { hunger = 0, hydration = 0 },
    svapo_evape2_box = { hunger = 0, hydration = 0 },
    svapo_smoke_box = { hunger = 0, hydration = 0 },
    svapo_vaporglow_box = { hunger = 0, hydration = 0 },
    svapo_sumo_box = { hunger = 0, hydration = 0 },
    svapo_smoke1a = { hunger = 0, hydration = 0 },
    svapo_smoke1b = { hunger = 0, hydration = 0 },
    svapo_smoke1c = { hunger = 0, hydration = 0 },
    svapo_smoke1d = { hunger = 0, hydration = 0 },
    svapo_evape1a = { hunger = 0, hydration = 0 },
    svapo_evape1b = { hunger = 0, hydration = 0 },
    svapo_evape1c = { hunger = 0, hydration = 0 },
    svapo_evape1d = { hunger = 0, hydration = 0 },
    svapo_vaporglow1a = { hunger = 0, hydration = 0 },
    svapo_vaporglow1b = { hunger = 0, hydration = 0 },
    svapo_vaporglow1c = { hunger = 0, hydration = 0 },
    svapo_vaporglow1d = { hunger = 0, hydration = 0 },
}
for k, v in pairs(vendingFood) do
    cfg.food[k] = v
end

return cfg
